### ISSUE TITLE
Extra Office Hours - Midterm prep

### ISSUE THREAD

**Issue by ohorban** [mikeizbicki/cmc-csci145-math166#115]
Can I suggest having extra office hours to prep for the upcoming midterm at
## Tuesday and Thursday 10am-12pm
This is just a proposition, so other times work to.

**Comment by sophiahuangg** [comment]
Bump! ^

**Comment by mikeizbicki** [comment]
That time on Thursday will work, there's regular office hours then on Tuesday, so a different time would be better.

**Comment by ohorban** [comment]
How does Tuesday 1-3pm sound like?

**Comment by mikeizbicki** [comment]
Tuesday 1-3pm sounds good.  In both cases, we'll do it in the math commons room.

**Comment by mikeizbicki** [comment]
I unfortunately have to cancel the scheduled 10am-12pm review session.  (My wife needed to make a last-minute doctors appointment and I'll have to watch our kids during this time.)

I will still be available for a review session later in the day if there's demand.  I suggest from 1-3pm, since that is the time we did before.  I will post the midterm after the review session.

Sorry about the last minute change :(

**Comment by ohorban** [comment]
^ 1-3 sounds good

**Comment by kevinm126** [comment]
Is there anyone for a later time say 2-4?

**Comment by afroCoderHanane** [comment]
+1 to kevin

**Comment by mikeizbicki** [comment]
Okay, we'll do 2-4 in the math commons room.

**Comment by DestrosCMC** [comment]
> Okay, we'll do 2-4 in the math commons room.

Some of us have class at 2:45pm so could the start time be a little earlier? Maybe 1:00pm?

**Comment by mikeizbicki** [comment]
Sure.  Marathon review session from 1-4pm today.  Feel free to come and go as your schedule allows.

**Comment by noahmbenjamin** [comment]
Absolutely tragic I have class from 1:15-4pm

**Comment by mikeizbicki** [comment]
@NBLEGO I'm on my way to my office right now.  I'd be happy to start answering questions as soon as I get there.
