### ISSUE TITLE
More Midterm 2 Practice Problems: Problem 10

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci145-math166#116]
If one of the use cases of the Hoeffding inequality is to bound the generalization error for finite hypothesis classes, why is the answer to question 10 False? 

It seems like the pocket algorithm is finite because it terminates after t iterations?

**Comment by mikeizbicki** [comment]
The answer to 10 is in fact False.

The perceptron hypothesis class is infinite because it is parameterized by $\mathbf w \in \mathbb R^d$.  The number of iterations of an algorithm that selects a hypothesis from a hypothesis class is unrelated to the size of that particular hypothesis class.  And every (useful) algorithm terminates after a finite number of iterations.  For example, stochastic gradient descent terminates after a finite number of iterations on infinite hypothesis classes.

One of the main motivations of introducing the VC dimension was to be able to place bounds on the generalization of the perceptron hypothesis class because the Hoeffding inequality was unable to do so.
