### ISSUE TITLE
T/F Question 12 and 13: Size of hypothesis class H{L2-4}?

### ISSUE THREAD

**Issue by ZiangXue** [mikeizbicki/cmc-csci145-math166#117]
We were thinking that the size of hypothesis class $H_{L2-4}$ should be 4, because the L2 norm is a scaler. However, if so it means that $H_{L2-4}$ has a smaller size than $H_{axis}$ and should have a larger in-sample error.

We can't confirm the size of that hypothesis class. Can someone share some insights?

**Comment by mikeizbicki** [comment]
You're correct that $H_{L2-4}$ is a smaller hypothesis class than $H_{axis2}$, but that doesn't **necessarily** mean that it will have smaller in-sample error.  In particular, for these two hypothesis classes, it's possible to generate 2 datasets where the first dataset has $E_{in}(g_{L2-4})=0$ and $E_{in}(g_{axis2}) > 0$, but the second dataset has $E_{in}(g_{L2-4})>0$ and $E_{in}(g_{axis2}) = 0$.

In order to **guarantee** that the in-sample error for the ERM of hypothesis class $\mathcal H_1$ is smaller than the ERM of another hypothesis class $\mathcal H_2$, you must have that $\mathcal H_2 \subset \mathcal H_1$.  It is not enough just to have that their number of elements or VC dimension be smaller.
