### ISSUE TITLE
PageRank slow runtime

### ISSUE THREAD

**Issue by oliverc1623** [mikeizbicki/cmc-csci145-math166#20]
Hello! This is kind of an ambiguous question because it could depend on my computer. I wrote the power method function for my PageRank algorithm. It's giving the correct results, however the runtime is pretty slow. More specifically, I'm getting higher iterations compared to the examples in the README.md. Is this indicative that I may have implemented the method incorrectly?

**Comment by mikeizbicki** [comment]
Hmm... you can reduce the runtime per iteration by using the `torch.sparse.addmm` function instead of the `torch.sparse.mm` function.  The former does a bunch of operations at the same time as the matrix multiplication and so is about 2-5x faster.  That shouldn't affect the number of iterations though.   The number of iterations should also be the same on every computer that runs the same code; the only difference will be how long each iteration takes.

My guess is that our implementations are calculating slightly different formulas, but that's okay.  There's a lot of slightly different ways to implement pagerank that are all equally valid from a data mining perspective even if they are computing technically different results.

As long as you're getting the right ordering of results on the `small.csv.gz` graph, you're good.
