### ISSUE TITLE
Question on Problem 6.4 Model Zoo

### ISSUE THREAD

**Issue by benfig1127** [mikeizbicki/cmc-csci145-math166#32]
@mikeizbicki Since I wasn't able to make it to the live class on Wednesday, I am trying to go off the pdf and the videos to fill in the Model Zoo notes. However, the last question is left blank on the notes so here is the answer that I was able to research and I wanted to check to see if I had the right idea:
```
K-neighrest neighbors is often a very good starting point when training model, especially when you need 

to learn a sophisticated (non-linear) pattern w/ a relatively low number of samples (and dimensions). 

Furthermore, KNN is not the most accurate method, but sometimes its more than sufficient and can be extremely fast. 
```

Anyone else that was in the live class, if you have feedback on my answer as well I would love to hear it! Thanks everyone :)

**Comment by mikeizbicki** [comment]
The answer I'm looking for is that the fundamental theorem of statistical learning provides bounds on the sample complexity based on the VC dimension for all datasets (and in particular the worst possible data set).  Since k-NN has VC-dim of infinity, it cannot work in this worst case scenario.  Many datasets, however, are not worst case datasets, and in this case k-NN can work.

In the coming weeks, we will see examples of worst case and not-worst case datasets.
