### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by hanaknight** [mikeizbicki/cmc-csci145-math166#49]
I got this error in the middle of running my program and I'm confused why this is happening because I thought the size of the target tensor should have been 64 anyway? (My code is below the error message). 

![image](https://user-images.githubusercontent.com/60402191/98455527-75d24600-21a4-11eb-9a61-1c21068aa777.png)

![image](https://user-images.githubusercontent.com/60402191/98455552-c5187680-21a4-11eb-97e4-cca3e38be03a.png)

**Comment by mikeizbicki** [comment]
This is a bug I intentionally inserted into the code.  The crash will always happen when `t=1686`, and that's why you're only required to run up to `t=1000` for the tensorboard plots.

The cause of the crash is that the number of data points is not evenly divisible by the batch size 64.  So on the very last iteration trough the dataset, there are fewer than 64 data points loaded.  The size of the tensors, however, is hard coded to be 64 rather than looking at the actual number of data points that were loaded, and this causes the crash.
