### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte

### ISSUE THREAD

**Issue by elizabethsong** [mikeizbicki/cmc-csci145-math166#59]
I've been getting this error when I run the code. I'm not sure what could be causing this since I haven't changed any code in train.py. Do you know what the problem could be?
<img width="978" alt="Screen Shot 2020-11-17 at 10 32 57 PM" src="https://user-images.githubusercontent.com/9876552/99479786-d855df80-2924-11eb-853a-509c33a2de0e.png">

**Comment by mikeizbicki** [comment]
It looks like you're somehow not using the same file that's on github.  I can tell this because you're line 151 (where the error message is generated) is different than line 151 in the uploaded file: https://github.com/mikeizbicki/cmc-csci145-math166/blob/fall2020/10_text_ii/train.py#L151

Big picture, this type of error happens when you somehow have a data file that is not encoded using utf-8.  All of the files I have posted on github, however, are encoded using utf-8.  So somehow the files you are using are not the same as the files on github.
