### ISSUE TITLE
Notes 1 Question 10 

### ISSUE THREAD

**Issue by sarahbashir** [mikeizbicki/cmc-csci145-math166#7]
I believe I understand that we want to find a matrix where B = A transpose. Confused about the other criteria that A and B should be satisfying in order to satisfy the conditions given in the question.. is there anything we should know about the number of 0's that should appear in either matrix or anything else?

**Comment by mikeizbicki** [comment]
One hint for finding A and B is start with the 2x2 case where each entry is a 1 or a 0.  There's only so many combinations of 1s and 0s, so you can try them all in just a few minutes, and you'll see a pattern about what causes the nnz to increase and decrease.

Once you see a pattern, generalize to the larger matrices.

**Comment by ethanashby** [comment]
Hi Mike, I'm confused re: why nnz(AB) can be different from nnz(B^T A^T)... let's say matrix AB has some number of nonzero entries. The transpose of AB, (AB)^T, should have the same number of nonzero entries as AB, because all we've done is flip the entries across the diagonal. So nnz(AB)=nnz((AB)^T). But (AB)^T=B^T*A^T. So it seems to me like nnz(AB) cannot be different from nnz(B^T A^T). Is this reasoning correct? Or am I missing something?

**Comment by mikeizbicki** [comment]
@ethanashby Your reasoning is exactly correct.

I had a typo on this problem, and I think I may have forgotten to point out the typo during class.  I've just uploaded the corrected version of the problem to github.  In summary, the condition should be that $nnz(AB) = O(1)$ and $nnz(BA) = \Omega(m^2)$.  The transposes should not be there because (as you correctly point out) the transposes cause you to get the same sparsity.
