### ISSUE TITLE
torch.sum() help

### ISSUE THREAD

**Issue by noahmbenjamin** [mikeizbicki/cmc-csci145-math166#93]
Hello! I am trying to create the 'a' vector, and I am having trouble with the torch.sum() function. I'm sure there are other issues with my code, probably with syntax too, but this is the method I have been trying to implement:

```
a = torch.zeros(len(self.P))
for j in range(len(self.P)):
     if torch.sum(self.P[j]) == 0:
            a[j] = 1
```

The line and error I am getting is:

```
  File "pagerank.py", line 161, in power_method
    if torch.sum(self.P[j]) == 0:
NotImplementedError: Could not run 'aten::sum.IntList_out' with arguments from the 'SparseCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::sum.IntList_out' is only available for these backends: [Dense, Metal, Conjugate, UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseXPU, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].
```

I tried looking this up but haven't found anything that fixes my issue. Any help is much appreciated!

Best,
Noah

**Comment by mikeizbicki** [comment]
My implementation uses the function `torch.sparse.sum` (see docs at https://pytorch.org/docs/stable/generated/torch.sparse.sum.html).  I call the function like `torch.sparse.sum(self.P, 1)` to sum over the rows of the P matrix, producing a vector of results.  I believe the fact that you are using `torch.sum` (which is intended for normal/dense tensors) instead of `torch.sparse.sum` (which is intended for sparse ones) is what's causing your error here.  In general, all the operations for sparse tensors sit inside the `torch.sparse` module.

PS.  I reformatted your issue above to put the code inside code blocks (using triple backticks) to make it more readable.  In general, anytime you're inserting code into github, you should put it in a code block like that.
